# **`MACHINE LEARNING INTRODUCTION ASSIGNMENT`**

### ***Importing necessary libraries***

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk

#### *Loading the data*

In [5]:
df=pd.read_csv("Dataset.csv")

## **`Data Exploration`**

In [7]:
df.shape# Havung a look at th shape in terms of (rows and columns)

(100, 3)

In [8]:
df.head()#First 5 rows of the dataset

   Country   Age   Salary
0    India  45.0  70000.0
1  Germany  26.0  56000.0
2   France  46.0  60000.0
3   France  31.0  72000.0
4    India  37.0  96000.0

In [9]:
df.tail() # last 5 rows of the dataset

   Country   Age   Salary
95   India  40.0  50000.0
96   India  57.0  68000.0
97   India  36.0  90000.0
98   India   NaN  72000.0
99   India  38.0  50000.0

In [10]:
df.info()# Information about the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  100 non-null    object
 1   Age      89 non-null     float64
 2   Salary   88 non-null     float64
dtypes: float64(2), object(1)
memory usage: 2.5+ KB

In [11]:
df.describe()# statistical summary

             Age        Salary
count  89.000000     88.000000
mean   42.325843  70204.545455
std    10.151999  16736.057220
min    25.000000  40000.000000
25%    34.000000  56000.000000
50%    41.000000  71000.000000
75%    52.000000  82500.000000
max    59.000000  98000.000000